apiVersion: v1
kind: Namespace
metadata:
  name: hello-testing-1-prod
  labels:
    environment-id: env_e967afa4-b615-47e7-87b2-8920efa541ae
    project-id: project_0505d45b-8466-40bb-b82c-066fff0df2a1
    project-name: hello-testing-1
    environment-name: prod
    organization-id: org_2ae217e1-d709-401d-94ae-f6d5cdb3ab42
